name: Build Python to EXE and Create GitHub Release

on:
  push:
    branches:
      - main   # 推送到 main 分支时触发
  workflow_dispatch:  # 支持手动运行

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 使用 PyInstaller 打包为 EXE
        run: |
          pyinstaller --noconfirm --onefile degree_sequence.py

      - name: 获取当前时间戳并创建 Git 标签
        id: get_timestamp
        run: |
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: 创建并推送 Git 标签
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ env.timestamp }}
          git push origin refs/tags/${{ env.timestamp }}

      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.timestamp }}  # 使用生成的时间戳作为标签名
          release_name: Auto-built EXE 版本 - ${{ env.timestamp }}
          draft: false
          prerelease: false

      - name: 上传 Release 资产
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, reference it with the output: `steps.<step_id>.outputs.<output_name>`
          asset_path: ./dist/degree_sequence.exe
          asset_name: degree_sequence_${{ env.timestamp }}.exe
          asset_content_type: application/x-msdownload