name: Build Python to EXE and Create GitHub Release

on:
  push:
    branches:
      - main   # 推送到 main 分支时触发
  workflow_dispatch:  # 支持手动运行

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 使用 PyInstaller 打包为 EXE
        run: |
          pyinstaller --noconfirm --onefile 图度序列.py

      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 使用 git tag 的名字
          release_name: Auto-built EXE 版本
          draft: false
          prerelease: false

      - name: 上传 Release 资产
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, reference it with the output: `steps.<step_id>.outputs.<output_name>`
          asset_path: ./dist/图度序列.exe
          asset_name: 图度序列.exe
          asset_content_type: application/x-msdownload
        